#!/usr/bin/env bash

if [ -d src/app/etc ]; then
  if [ ! -e src/app/etc/env.php ]; then
    cp .docker/users/env.sample.php src/app/etc/env.php;
  fi
fi

docker-compose up -d && \
echo "
========================================

      🌎 Web server: http://localhost/

      ⚙️ Admin: http://localhost/admin

            user: admin
            password: admin123

      ⚙️ PHPMyAdmin: http://localhost:8090

========================================"
